// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dark: typeof import('./.vitepress/vitepress/components/icons/dark.vue')['default']
    IRiMenuLine: typeof import('~icons/ri/menu-line')['default']
    Light: typeof import('./.vitepress/vitepress/components/icons/light.vue')['default']
    PowerFunctionTable: typeof import('./.vitepress/vitepress/components/globals/power-function-table.vue')['default']
    ThemeAwareImage: typeof import('./.vitepress/vitepress/components/globals/theme-aware-image.vue')['default']
    ToggleButton: typeof import('./.vitepress/vitepress/components/icons/toggle-button.vue')['default']
    ToggleSidebarBtn: typeof import('./.vitepress/vitepress/components/subnav/toggle-sidebar-btn.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDocContent: typeof import('./.vitepress/vitepress/components/vp-doc-content.vue')['default']
    VpHamburger: typeof import('./.vitepress/vitepress/components/navbar/vp-hamburger.vue')['default']
    VpLink: typeof import('./.vitepress/vitepress/components/common/vp-link.vue')['default']
    VpMenu: typeof import('./.vitepress/vitepress/components/navbar/vp-menu.vue')['default']
    VpMenuExtension: typeof import('./.vitepress/vitepress/components/navbar/vp-menu-extension.vue')['default']
    VpMenuLink: typeof import('./.vitepress/vitepress/components/navbar/vp-menu-link.vue')['default']
    VpNav: typeof import('./.vitepress/vitepress/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./.vitepress/vitepress/components/vp-navbar.vue')['default']
    VpNavFull: typeof import('./.vitepress/vitepress/components/vp-nav-full.vue')['default']
    VpNotFound: typeof import('./.vitepress/vitepress/components/vp-not-found.vue')['default']
    VpOverlay: typeof import('./.vitepress/vitepress/components/vp-overlay.vue')['default']
    VpPageNav: typeof import('./.vitepress/vitepress/components/doc-content/vp-page-nav.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSidebarLink: typeof import('./.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue')['default']
    VpSocialLink: typeof import('./.vitepress/vitepress/components/navbar/vp-social-link.vue')['default']
    VpSocialLinks: typeof import('./.vitepress/vitepress/components/navbar/vp-social-links.vue')['default']
    VpSubnav: typeof import('./.vitepress/vitepress/components/vp-subnav.vue')['default']
    VpTableOfContent: typeof import('./.vitepress/vitepress/components/doc-content/vp-table-of-content.vue')['default']
    VpTableOfContentSidebar: typeof import('./.vitepress/vitepress/components/vp-table-of-content-sidebar.vue')['default']
    VpThemeToggler: typeof import('./.vitepress/vitepress/components/navbar/vp-theme-toggler.vue')['default']
    VpTocSidebar: typeof import('./.vitepress/vitepress/components/vp-toc-sidebar.vue')['default']
  }
}

export {}
